"""Markdown report generation utilities."""

from pathlib import Path
from datetime import datetime

from ..models.schemas import DesignReport


def generate_report_markdown(report: DesignReport) -> str:
    """Generate a markdown report from a DesignReport."""
    lines = [
        "# Interior Design Report",
        "",
        f"**Session ID:** {report.session_id}",
        f"**Generated:** {datetime.now().strftime('%B %d, %Y %I:%M %p')}",
        "",
        "---",
        "",
        "## Executive Summary",
        "",
        report.summary,
        "",
        "---",
        "",
    ]

    # Room Analyses
    if report.room_analyses:
        lines.append("## Room Analysis")
        lines.append("")

        for i, analysis in enumerate(report.room_analyses, 1):
            lines.append(f"### Room {i}: {analysis.room_type.title()}")
            lines.append("")
            lines.append(f"**Current Style:** {analysis.current_style}")
            if analysis.estimated_dimensions:
                lines.append(f"**Estimated Size:** {analysis.estimated_dimensions}")
            lines.append(f"**Lighting:** {analysis.lighting_assessment}")
            lines.append("")

            if analysis.existing_furniture:
                lines.append("**Existing Furniture:**")
                for item in analysis.existing_furniture:
                    lines.append(f"- {item}")
                lines.append("")

            if analysis.color_palette:
                lines.append(f"**Color Palette:** {', '.join(analysis.color_palette)}")
                lines.append("")

            if analysis.strengths:
                lines.append("**Strengths:**")
                for strength in analysis.strengths:
                    lines.append(f"- {strength}")
                lines.append("")

            if analysis.improvement_opportunities:
                lines.append("**Improvement Opportunities:**")
                for opp in analysis.improvement_opportunities:
                    lines.append(f"- {opp}")
                lines.append("")

        lines.append("---")
        lines.append("")

    # Recommendations
    if report.recommendations:
        lines.append("## Design Recommendations")
        lines.append("")

        for i, rec in enumerate(report.recommendations, 1):
            priority_emoji = {"high": "!!!", "medium": "!!", "low": "!"}
            lines.append(f"### {i}. {rec.category.title()} ({rec.priority.upper()} priority)")
            lines.append("")
            lines.append(f"**Current State:** {rec.current_state}")
            lines.append("")
            lines.append(f"**Recommendation:** {rec.recommendation}")
            lines.append("")

            if rec.estimated_cost:
                lines.append(f"**Estimated Cost:** {rec.estimated_cost}")
                lines.append("")

            if rec.product_suggestions:
                lines.append("**Suggested Products:**")
                for product in rec.product_suggestions:
                    lines.append(f"- {product}")
                lines.append("")

        lines.append("---")
        lines.append("")

    # Generated Images
    if report.generated_images:
        lines.append("## AI-Generated Visualizations")
        lines.append("")

        for gen_img in report.generated_images:
            lines.append(f"### {gen_img.description}")
            lines.append("")
            # Use relative path for markdown
            rel_path = Path(gen_img.path).name
            lines.append(f"![{gen_img.description}](./generated/{rel_path})")
            lines.append("")
            lines.append(f"*Prompt: {gen_img.prompt_used}*")
            lines.append("")

        lines.append("---")
        lines.append("")

    lines.append("*Generated by Interior Design AI Assistant*")

    return "\n".join(lines)


def save_report(
    report: DesignReport,
    session_dir: Path,
    output_format: str = "pdf",
) -> Path:
    """Save the design report as PDF/markdown and JSON.

    Args:
        report: The design report
        session_dir: Session directory to save files
        output_format: 'pdf' or 'md'

    Returns:
        Path to the main report file (PDF or markdown)
    """
    # Always save JSON
    json_path = session_dir / "analysis.json"
    json_content = report.model_dump_json(indent=2)
    json_path.write_text(json_content)

    # Always save markdown
    md_path = session_dir / "report.md"
    md_content = generate_report_markdown(report)
    md_path.write_text(md_content)

    # Generate PDF if requested
    if output_format == "pdf":
        from .pdf import generate_pdf_report

        pdf_path = session_dir / "report.pdf"
        generate_pdf_report(
            report,
            pdf_path,
            original_images=list(report.original_images) if report.original_images else None,
        )
        return pdf_path

    return md_path
